<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Financial Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #ddd;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #2c3e50;
        }
        .meta {
            margin-bottom: 30px;
            color: #666;
            font-size: 10px;
        }
        .building-section {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .building-title {
            background-color: #f8f9fa;
            padding: 8px;
            font-weight: bold;
            font-size: 14px;
            border-left: 4px solid #0d6efd;
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }
        th, td {
            border: 1px solid #dee2e6;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #e9ecef;
            font-weight: bold;
        }
        .text-end {
            text-align: right;
        }
        .text-success { color: #198754; }
        .text-danger { color: #dc3545; }
        .arrears-table {
            width: 90%;
            margin-left: auto;
            margin-right: auto;
            font-size: 11px;
        }
        .arrears-header {
            font-weight: bold;
            color: #dc3545;
            margin-top: 5px;
            margin-bottom: 5px;
            margin-left: 20px;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Financial Report</h1>
        <div class="meta">
            Generated by: {{ $generated_by }} | Date: {{ $date }}
        </div>
    </div>

    @foreach($reportData as $data)
    <div class="building-section">
        <div class="building-title">{{ $data['building']->name }}</div>
        
        <!-- Financial Summary -->
        <table>
            <thead>
                <tr>
                    <th class="text-end">Total Income</th>
                    <th class="text-end">Total Expenses</th>
                    <th class="text-end">Net Cash Flow</th>
                    <th class="text-end">Total Arrears</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="text-end text-success">{{ number_format($data['financials']['income'], 2) }}</td>
                    <td class="text-end text-danger">{{ number_format($data['financials']['expense'], 2) }}</td>
                    <td class="text-end" style="font-weight: bold;">{{ number_format($data['financials']['cashflow'], 2) }}</td>
                    <td class="text-end text-danger" style="font-weight: bold;">{{ number_format($data['financials']['outstanding'], 2) }}</td>
                </tr>
            </tbody>
        </table>

        <!-- Outstanding Details -->
        @if(count($data['arrears_details']) > 0)
        <div class="arrears-header">Outstanding Rent Details</div>
        <table class="arrears-table">
            <thead>
                <tr>
                    <th width="30%">Unit</th>
                    <th width="40%">Tenant</th>
                    <th width="30%" class="text-end">Amount Due</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['arrears_details'] as $arrear)
                <tr>
                    <td>{{ $arrear['unit'] }}</td>
                    <td>{{ $arrear['tenant'] }}</td>
                    <td class="text-end text-danger">{{ number_format($arrear['amount'], 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <div style="margin-left: 20px; font-style: italic; color: #198754; font-size: 11px;">
            No outstanding rent for this building.
        </div>
        @endif
    </div>
    @endforeach

    <div class="footer">
        Okaro & Associates Property Management System
    </div>
</body>
</html>
