<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Building Financial Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #ddd;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #2c3e50;
        }
        .meta {
            margin-bottom: 30px;
            color: #666;
            font-size: 10px;
        }
        .section-title {
            background-color: #f8f9fa;
            padding: 8px;
            font-weight: bold;
            font-size: 14px;
            border-left: 4px solid #0d6efd;
            margin-top: 20px;
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }
        th, td {
            border: 1px solid #dee2e6;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #e9ecef;
            font-weight: bold;
        }
        .text-end {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .text-success { color: #198754; }
        .text-danger { color: #dc3545; }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $building->name }} - Financial Report</h1>
        <div class="meta">
            Generated by: {{ $generated_by }} | Date: {{ $date }}
        </div>
    </div>

    <!-- Summary Section -->
    <div class="section-title">Financial Summary</div>
    <table>
        <thead>
            <tr>
                <th class="text-end">Total Income</th>
                <th class="text-end">Total Expenses</th>
                <th class="text-end">Net Cash Flow</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-end text-success">{{ number_format($summary['income'], 2) }}</td>
                <td class="text-end text-danger">{{ number_format($summary['expense'], 2) }}</td>
                <td class="text-end" style="font-weight: bold;">{{ number_format($summary['cashflow'], 2) }}</td>
            </tr>
        </tbody>
    </table>

    <!-- Tenant Records Section -->
    <div class="section-title">Tenant Records</div>
    @if(count($rents) > 0)
    <table>
        <thead>
            <tr>
                <th width="15%">Unit</th>
                <th width="25%">Tenant</th>
                <th width="15%">Start Date</th>
                <th width="15%" class="text-end">Annual Rent</th>
                <th width="15%" class="text-end">Total Paid</th>
                <th width="15%" class="text-end">Outstanding</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rents as $rent)
            <tr>
                <td>{{ $rent['unit'] }}</td>
                <td>{{ $rent['tenant'] }}</td>
                <td>{{ $rent['start_date']->format('Y-m-d') }}</td>
                <td class="text-end">{{ number_format($rent['annual_rent'], 2) }}</td>
                <td class="text-end text-success">{{ number_format($rent['paid'], 2) }}</td>
                <td class="text-end {{ $rent['outstanding'] > 0 ? 'text-danger' : 'text-success' }}">
                    {{ number_format($rent['outstanding'], 2) }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p style="font-style: italic; color: #666;">No active tenant records found.</p>
    @endif

    <!-- Expenses Section -->
    <div class="section-title">Expenses Breakdown</div>
    @if($expenses->count() > 0)
    <table>
        <thead>
            <tr>
                <th width="15%">Date</th>
                <th width="20%">Category</th>
                <th width="45%">Description</th>
                <th width="20%" class="text-end">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($expenses as $expense)
            <tr>
                <td>{{ $expense->entry_date->format('Y-m-d') }}</td>
                <td>{{ $expense->category }}</td>
                <td>{{ $expense->description }}</td>
                <td class="text-end text-danger">{{ number_format($expense->amount, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p style="font-style: italic; color: #666;">No expenses recorded for this building.</p>
    @endif

    <div class="footer">
        Okaro & Associates Property Management System
    </div>
</body>
</html>
