@extends('layouts.app')

@section('content')
@if(auth()->user()->isAccountant() && !auth()->user()->isAdmin())
<style>
    #reportViewRoot.report-protect {
        user-select: none;
        -webkit-user-select: none;
    }
    #reportViewRoot.report-protect::after {
        content: "CONFIDENTIAL • {{ auth()->user()->email }} • {{ now()->format('Y-m-d H:i') }}";
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(-20deg);
        font-size: 42px;
        font-weight: 700;
        color: rgba(0, 0, 0, 0.10);
        pointer-events: none;
        z-index: 9999;
        white-space: nowrap;
    }
    body.report-obscured #reportViewRoot {
        filter: blur(12px);
    }
    @media print {
        #reportViewRoot {
            display: none !important;
        }
        body::before {
            content: "Printing disabled";
            display: block;
            padding: 40px;
            font-size: 22px;
        }
    }
</style>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const root = document.getElementById('reportViewRoot');
        if (root) {
            root.classList.add('report-protect');
        }

        document.addEventListener('contextmenu', function (e) {
            if (root && root.contains(e.target)) {
                e.preventDefault();
            }
        }, true);

        document.addEventListener('keydown', function (e) {
            const key = (e.key || '').toLowerCase();
            if ((e.ctrlKey || e.metaKey) && (key === 'p' || key === 's' || key === 'c')) {
                e.preventDefault();
            }
            if (e.key === 'PrintScreen') {
                document.body.classList.add('report-obscured');
                setTimeout(function () {
                    document.body.classList.remove('report-obscured');
                }, 1500);
                e.preventDefault();
            }
        }, true);

        document.addEventListener('visibilitychange', function () {
            if (document.visibilityState !== 'visible') {
                document.body.classList.add('report-obscured');
                return;
            }
            document.body.classList.remove('report-obscured');
        });
    });
</script>
@endif

<div class="container-fluid py-4" id="reportViewRoot">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <div>
            <h1 class="h3 mb-0">Report View</h1>
            <div class="text-muted small">Generated by: {{ $generated_by }} • Date: {{ $date }}</div>
        </div>
        <div class="btn-toolbar">
            <a href="{{ route('accounting.index') }}" class="btn btn-outline-secondary btn-sm">
                <i class="bi bi-arrow-left me-1"></i> Back
            </a>
        </div>
    </div>

    @if($mode === 'single')
        <div class="card shadow-sm border-0 mb-3">
            <div class="card-header bg-white">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="fw-bold text-primary">{{ $building->name }}</div>
                    <div class="text-muted small">{{ $building->address }}</div>
                </div>
            </div>
            <div class="card-body">
                <div class="row g-3 mb-3">
                    <div class="col-md-3">
                        <div class="border rounded p-2 bg-light">
                            <div class="text-muted small">Total Income</div>
                            <div class="fw-bold text-success">₦{{ number_format($summary['income'], 2) }}</div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="border rounded p-2 bg-light">
                            <div class="text-muted small">Total Expenses</div>
                            <div class="fw-bold text-danger">₦{{ number_format($summary['expense'], 2) }}</div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="border rounded p-2 bg-light">
                            <div class="text-muted small">Net Cash Flow</div>
                            <div class="fw-bold">₦{{ number_format($summary['cashflow'], 2) }}</div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="border rounded p-2 bg-light">
                            <div class="text-muted small">Outstanding</div>
                            <div class="fw-bold text-danger">₦{{ number_format($summary['outstanding'], 2) }}</div>
                        </div>
                    </div>
                </div>

                <h6 class="fw-bold mb-2">Tenant Records</h6>
                <div class="table-responsive mb-4">
                    <table class="table table-sm table-striped align-middle">
                        <thead class="table-light">
                            <tr>
                                <th>Unit</th>
                                <th>Tenant</th>
                                <th>Start</th>
                                <th class="text-end">Annual</th>
                                <th class="text-end">Paid</th>
                                <th class="text-end">Outstanding</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($rents as $rent)
                                <tr>
                                    <td>{{ $rent['unit'] }}</td>
                                    <td>{{ $rent['tenant'] }}</td>
                                    <td>{{ $rent['start_date'] ? $rent['start_date']->format('Y-m-d') : '' }}</td>
                                    <td class="text-end">₦{{ number_format($rent['annual_rent'], 2) }}</td>
                                    <td class="text-end text-success">₦{{ number_format($rent['paid'], 2) }}</td>
                                    <td class="text-end {{ $rent['outstanding'] > 0 ? 'text-danger' : 'text-success' }}">₦{{ number_format($rent['outstanding'], 2) }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="6" class="text-muted text-center py-3">No active tenant records.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>

                <h6 class="fw-bold mb-2">Expenses</h6>
                <div class="table-responsive">
                    <table class="table table-sm table-striped align-middle">
                        <thead class="table-light">
                            <tr>
                                <th>Date</th>
                                <th>Category</th>
                                <th>Description</th>
                                <th class="text-end">Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($expenses as $expense)
                                <tr>
                                    <td>{{ $expense->entry_date ? $expense->entry_date->format('Y-m-d') : '' }}</td>
                                    <td>{{ $expense->category }}</td>
                                    <td>{{ $expense->description }}</td>
                                    <td class="text-end text-danger">₦{{ number_format($expense->amount, 2) }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4" class="text-muted text-center py-3">No expenses recorded.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    @else
        <div class="card shadow-sm border-0">
            <div class="card-body">
                @foreach($reportData as $data)
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <div class="fw-bold text-primary">{{ $data['building']->name }}</div>
                        <a href="{{ route('accounting.report', ['building_id' => $data['building']->id]) }}" class="btn btn-outline-primary btn-sm">
                            <i class="bi bi-eye me-1"></i> View
                        </a>
                    </div>
                    <div class="table-responsive mb-3">
                        <table class="table table-sm table-bordered align-middle">
                            <thead class="table-light">
                                <tr>
                                    <th class="text-end">Income</th>
                                    <th class="text-end">Expenses</th>
                                    <th class="text-end">Cash Flow</th>
                                    <th class="text-end">Outstanding</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-end text-success">₦{{ number_format($data['financials']['income'], 2) }}</td>
                                    <td class="text-end text-danger">₦{{ number_format($data['financials']['expense'], 2) }}</td>
                                    <td class="text-end fw-bold">₦{{ number_format($data['financials']['cashflow'], 2) }}</td>
                                    <td class="text-end fw-bold text-danger">₦{{ number_format($data['financials']['outstanding'], 2) }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                @endforeach
            </div>
        </div>
    @endif
</div>
@endsection

